### ISSUE TITLE
UEFI signature error

### ISSUE THREAD

**Issue by ooxi** [grml/grml2usb#17]
I copied [grml96-full 2017.05](http://download.grml.org/grml96-full_2017.05.iso) to an USB stick using UNetbootin. While this method works with the Windows 10 image, my laptop does not want to boot from the USB stick containing grml, complaining about a signature error.

Now I'm wondering: does grml support secure boot (e.g. by using grml2usb instead of UNetbootin) or do I have to disable secure boot in able to use grml?

**Comment by mika** [comment]
The stable Grml releases don't support SecureBoot yet, though since quite some time our daily ISOs (available at http://daily.grml.org/) support SecureBoot, the upcoming stable release will support SecureBoot as well. Considering this as resolved, please re-open or file a new bugreport if you should notice any further issues. Thanks! :)
